default['ruby-env']['user'] = "deploy"
default['ruby-env']['group'] = "deploy"
default['ruby-env']['version'] = "2.2.2"
default['ruby-env']['rbenv_url'] = "https://github.com/sstephenson/rbenv"
default['ruby-env']['ruby-build_url'] = "https://github.com/sstephenson/ruby-build"
